### ISSUE TITLE
Error: undefined method `undent' for an instance of String

### ISSUE THREAD

**Issue by gorham3690** [guitorri/homebrew-tap#12]
Trying to install qucs 0.20 on a MacBook pro running Sonoma 14.2.1, here is what happens:

==> Installing guitorri/tap/qucs
==> Patching
==> Applying patch-configure-0.0.19.patch
patching file 'qucs/configure'
==> ./configure --disable-sdk --disable-doc
==> make install
Warning: Formula cartr/qt4/qt was renamed to cartr/qt4/qt-legacy-formula.
Warning: Formula cartr/qt4/qt was renamed to cartr/qt4/qt-legacy-formula.
Error: undefined method `undent' for an instance of String
/usr/local/Homebrew/Library/Taps/guitorri/homebrew-tap/qucs.rb:42:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:22:in `caveats'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/lib/ruby/3.3.0/forwardable.rb:234:in `empty?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:781:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:855:in `finish'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:238:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/install.rb:301:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:300:in `each'
/usr/local/Homebrew/Library/Homebrew/install.rb:300:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:297:in `run'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'

Any thoughts on where "undent" is supposed to be found?

**Comment by gorham3690** [comment]
I guess I should have searched this error before posting, found a workaround already discussed.
